behaviors:

  MaleAgentV:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 80000000
    time_horizon: 1000
    summary_freq: 20000

  FemaleAgent:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 80000000
    time_horizon: 1000
    summary_freq: 20000

environment_parameters:
  targetCountF:
    curriculum:
      - name: SearchEasy
        value: 2
        completion_criteria:
          measure: progress
          signal_smoothing: true
          min_lesson_length: 15
          threshold: 0.2
          behavior: FemaleAgent
      - name: SearchHard
        value: 4
        completion_criteria:
          measure: progress
          signal_smoothing: true
          min_lesson_length: 15
          threshold: 0.6
          require_reset: true
          behavior: FemaleAgent
      - name: HideSeek
        value: 0
  maleImmobility:
    curriculum:
      - name: ImmobilePhase
        value: 1
        completion_criteria:
          measure: progress
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 0.4
          behavior: MaleAgentV
      - name: MobilePhase
        value: 0
        completion_criteria:
          measure: progress
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 1.0
          require_reset: true
          behavior: MaleAgentV
  targetCountM:
    curriculum:
      - name: SearchEasy
        value: 2
        completion_criteria:
          measure: progress
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 0.4
          behavior: MaleAgentV
      - name: SearchHard
        value: 4
        completion_criteria:
          measure: progress
          signal_smoothing: true
          min_lesson_length: 2
          threshold: 0.6
          require_reset: true
          behavior: MaleAgentV
      - name: HideSeek
        value: 0